name: "Meross Local Broker Addon"
version: "0.0.1-alpha47"
description: "Enables LAN-ONLY broker, avoiding Meross Cloud usage."
slug: "meross_local_broker"
image: "ghcr.io/albertogeniola/{arch}-meross_local_broker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  2001/tcp: 2001
  2003/tcp: 2003
  10001/tcp: 10001
ports_description:
  2001/tcp: "MQTT Broker port"
  2003/tcp: "HTTP API port"
  10001/tcp: "Remote debugger port"
ingress: true
ingress_port: 2003
startup: services
panel_icon: mdi:power-socket-us
panel_title: Local Meross Broker
host_dbus: true
homeassistant: "1.0.0"
options:
  reinit_db: false
  advertise: true
  debug_mode: false
schema:
  reinit_db: "bool"
  advertise: "bool"
  debug_mode: "bool"
